### ISSUE TITLE
Libcurl Error

### ISSUE THREAD

**Issue by dchun** [ClickSend/clicksend-ruby#1]
After building and installing the ruby gem for clicksend when testing the account_get method via the AccountApi I get the following error:

```
ETHON: Libcurl initialized
objc[65695]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[65695]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

I'm running ruby 2.6.3, rails 6.0.0, and my dev machine is macOS High Sierra 10.13.6. The generated gem version is 5.0.56.

Any ideas on what might be causing this error?

**Comment by dchun** [comment]
It was an OS issues and resolved it by disabling warning signals

**Comment by coderdave** [comment]
For anyone that stumbles on this and doesn't know how to set it: https://stackoverflow.com/questions/52671926/rails-may-have-been-in-progress-in-another-thread-when-fork-was-called
